// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//  ucd-generate.exe property-bool ucd-10.0.0 --include WHITE_SPACE,PATTERN_WHITE_SPACE --chars
//
// ucd-generate 0.2.6 is available on crates.io.

pub const BY_NAME: &'static [(&'static str, &'static [(char, char)])] =
    &[("Pattern_White_Space", PATTERN_WHITE_SPACE), ("White_Space", WHITE_SPACE)];

pub const PATTERN_WHITE_SPACE: &'static [(char, char)] = &[
    ('\t', '\r'),
    (' ', ' '),
    ('\u{85}', '\u{85}'),
    ('\u{200e}', '\u{200f}'),
    ('\u{2028}', '\u{2029}'),
];

pub const WHITE_SPACE: &'static [(char, char)] = &[
    ('\t', '\r'),
    (' ', ' '),
    ('\u{85}', '\u{85}'),
    ('\u{a0}', '\u{a0}'),
    ('\u{1680}', '\u{1680}'),
    ('\u{2000}', '\u{200a}'),
    ('\u{2028}', '\u{2029}'),
    ('\u{202f}', '\u{202f}'),
    ('\u{205f}', '\u{205f}'),
    ('\u{3000}', '\u{3000}'),
];
